name: NestJs CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v3

      - name: Node.js o'rnatish
        uses: actions/setup-node@v3
        with:
         node-version: 18.x

      - name: Dependenciyalarni o'rnatish
        run : npm ci

      - name: Lint tekshirish
        run: npm run lint

      - name: Testlarni ishga tushirish
        run: npm run test

      - name: Build qilish
        run: npm run build

    deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: EC2 ga SSH ulanish va deploy qilish
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/nestjsTest
            git pull origin main
            npm install --production
            npm run build
            pm2 restart server
